# -*- coding: utf-8 -*-

from gettext import gettext as _



LEVEL1 = [
        2,
        _('Cities'),
        ['lineasDepto', 'capitales', 'ciudades'],
        [],
[
	# toliary
	(_('Manambato'), _("It's in %s") % _('Toliary')),
	(_('Mahatalaky'), _("It's in %s") % _('Toliary')),
	(_('Tolanaro'), _("It's in %s") % _('Toliary')),
	(_('Beanky'), _("It's in %s") % _('Toliary')),
	(_('Talaky'), _("It's in %s") % _('Toliary')),
	(_('Betanty'), _("It's in %s") % _('Toliary')),
	(_('Lavanono'), _("It's in %s") % _('Toliary')),
	(_('Beloha'), _("It's in %s") % _('Toliary')),
	(_('Etrobeke'), _("It's in %s") % _('Toliary')),
	(_('Androka'), _("It's in %s") % _('Toliary')),
	(_('Ankazoabo'), _("It's in %s") % _('Toliary')),
	(_('Vohombe'), _("It's in %s") % _('Toliary')),
	(_('Efoetse'), _("It's in %s") % _('Toliary')),
	(_('Beheloka'), _("It's in %s") % _('Toliary')),
	(_('Betioky'), _("It's in %s") % _('Toliary')),
	(_('Anakao'), _("It's in %s") % _('Toliary')),
	(_('Bezaha'), _("It's in %s") % _('Toliary')),
	(_('Ankilarivo'), _("It's in %s") % _('Toliary')),
	(_('Manombo Atsimo'), _("It's in %s") % _('Toliary')),
	(_('Tanambao'), _("It's in %s") % _('Toliary')),
	(_('Ambohitsabo'), _("It's in %s") % _('Toliary')),
	(_('Benfandriana Atsimo'), _("It's in %s") % _('Toliary')),
	(_('Andavadoaka'), _("It's in %s") % _('Toliary')),
	(_('Morombe'), _("It's in %s") % _('Toliary')),
	(_('Nosy Ambositra'), _("It's in %s") % _('Toliary')),
	(_('Ambohibe'), _("It's in %s") % _('Toliary')),
	(_('Ankoba'), _("It's in %s") % _('Toliary')),
	(_('Manja'), _("It's in %s") % _('Toliary')),
	(_('Belo'), _("It's in %s") % _('Toliary')),
	(_('Manometimay'), _("It's in %s") % _('Toliary')),
	(_('Morondava'), _("It's in %s") % _('Toliary')),
	(_('Mandronarivo'), _("It's in %s") % _('Toliary')),
	(_('Malaimbandy'), _("It's in %s") % _('Toliary')),
	(_('Beroboka Avaratra'), _("It's in %s") % _('Toliary')),
	(_('Belo Tsiribihina'), _("It's in %s") % _('Toliary')),
	(_('Andramasay'), _("It's in %s") % _('Toliary')),
	(_('Adabozato'), _("It's in %s") % _('Toliary')),
	(_('Behamotra'), _("It's in %s") % _('Toliary')),
	(_('Appontement'), _("It's in %s") % _('Toliary')),
	# mahajanga
	(_('Bekopaka'), _("It's in %s") % _('Mahajanga')),
	(_('Bemamba'), _("It's in %s") % _('Mahajanga')),
	(_('Ankiliroa'), _("It's in %s") % _('Mahajanga')),
	(_('Maintirano'), _("It's in %s") % _('Mahajanga')),
	(_('Ankatrafay'), _("It's in %s") % _('Mahajanga')),
	(_('Tambohorano'), _("It's in %s") % _('Mahajanga')),
	(_('Onara'), _("It's in %s") % _('Mahajanga')),
	(_('Makaraingo'), _("It's in %s") % _('Mahajanga')),
	(_('Andasibe'), _("It's in %s") % _('Mahajanga')),
	(_('Besalampy'), _("It's in %s") % _('Mahajanga')),
	(_('Vilamatsa'), _("It's in %s") % _('Mahajanga')),
	(_('Ambohipaky'), _("It's in %s") % _('Mahajanga')),
	(_('Maria'), _("It's in %s") % _('Mahajanga')),
	(_('Antanandava'), _("It's in %s") % _('Mahajanga')),
	(_('Ambakireny'), _("It's in %s") % _('Mahajanga')),
	(_('Manakana'), _("It's in %s") % _('Mahajanga')),
	(_('Ampandrana'), _("It's in %s") % _('Mahajanga')),
	(_('Besakay'), _("It's in %s") % _('Mahajanga')),
	(_('Matsitso'), _("It's in %s") % _('Mahajanga')),
	(_('Ambato Boeny'), _("It's in %s") % _('Mahajanga')),
	(_('Marovoay'), _("It's in %s") % _('Mahajanga')),
	(_('Morafeno'), _("It's in %s") % _('Mahajanga')),
	(_('Tsianinkira'), _("It's in %s") % _('Mahajanga')),
	(_('Mandritsara'), _("It's in %s") % _('Mahajanga')),
	(_('Anjajavy'), _("It's in %s") % _('Mahajanga')),
	(_('Analava'), _("It's in %s") % _('Mahajanga')),
	(_('Maromandia'), _("It's in %s") % _('Mahajanga')),
	(_('Antanantanana'), _("It's in %s") % _('Mahajanga')),
	(_('Antsahabe'), _("It's in %s") % _('Mahajanga')),
	(_('Marovotry'), _("It's in %s") % _('Mahajanga')),
	# antsiranana
	(_('Ampohana'), _("It's in %s") % _('Antsiranana')),
	(_('Ambanja'), _("It's in %s") % _('Antsiranana')),
	(_('Ambilobe'), _("It's in %s") % _('Antsiranana')),
	(_('Ambatoharanana'), _("It's in %s") % _('Antsiranana')),
	(_('Bobasakoa'), _("It's in %s") % _('Antsiranana')),
	(_('Bemanevikabe'), _("It's in %s") % _('Antsiranana')),
	(_('Anjiabe'), _("It's in %s") % _('Antsiranana')),
	(_('Irodo'), _("It's in %s") % _('Antsiranana')),
	(_('Ampisikinana'), _("It's in %s") % _('Antsiranana')),
	(_('Daraina'), _("It's in %s") % _('Antsiranana')),
	(_('Apondra'), _("It's in %s") % _('Antsiranana')),
	(_('Zarambavy'), _("It's in %s") % _('Antsiranana')),
	(_('Doany'), _("It's in %s") % _('Antsiranana')),
	(_('Tanambao-Daoud'), _("It's in %s") % _('Antsiranana')),
	(_('Sambava'), _("It's in %s") % _('Antsiranana')),
	(_('Farahalana'), _("It's in %s") % _('Antsiranana')),
	(_('Andranofotsy'), _("It's in %s") % _('Antsiranana')),
	(_('Antalaha'), _("It's in %s") % _('Antsiranana')),
	(_('Ambohitralanana'), _("It's in %s") % _('Antsiranana')),
	(_('Ampanavoana'), _("It's in %s") % _('Antsiranana')),
	# tomasina
	(_('Maroantsetra'), _("It's in %s") % _('Tomasina')),
	(_('Seranambe'), _("It's in %s") % _('Tomasina')),
	(_('Antanambe'), _("It's in %s") % _('Tomasina')),
	(_('Ambodiatafana'), _("It's in %s") % _('Tomasina')),
	(_('Vohilava'), _("It's in %s") % _('Tomasina')),
	(_('Andrangazaha'), _("It's in %s") % _('Tomasina')),
	(_('Fenoarivo Atsinanana'), _("It's in %s") % _('Tomasina')),
	(_('Amparafaravola'), _("It's in %s") % _('Tomasina')),
	(_('Ambatondrazaka'), _("It's in %s") % _('Tomasina')),
	(_('Ambila-Lemaitso'), _("It's in %s") % _('Tomasina')),
	(_('Moramanga'), _("It's in %s") % _('Tomasina')),
	(_('Vohitrampasina'), _("It's in %s") % _('Tomasina')),
	(_('Vatomandry'), _("It's in %s") % _('Tomasina')),
	(_('Ambodiharina'), _("It's in %s") % _('Tomasina')),
	(_('Masomeloka'), _("It's in %s") % _('Tomasina')),
	# Antananarivo
	(_('Ambohimena'), _("It's in %s") % _('Antananarivo')),
	(_('Fiadanana'), _("It's in %s") % _('Antananarivo')),
	(_('Tsiroanomandidy'), _("It's in %s") % _('Antananarivo')),
	(_('Sakay'), _("It's in %s") % _('Antananarivo')),
	(_('Ambatolampy'), _("It's in %s") % _('Antananarivo')),
	(_('Antsirabe'), _("It's in %s") % _('Antananarivo')),
	# fianarantsoa
	(_('Lopary'), _("It's in %s") % _('Fianarantsoa')),
	(_('Ranomena'), _("It's in %s") % _('Fianarantsoa')),
	(_('Isahara'), _("It's in %s") % _('Fianarantsoa')),
	(_('Sandravinany'), _("It's in %s") % _('Fianarantsoa')),
	(_('Soavina'), _("It's in %s") % _('Fianarantsoa')),
	(_('Nosy-Varika'), _("It's in %s") % _('Fianarantsoa')),
	(_('Amborompotsy'), _("It's in %s") % _('Fianarantsoa')),
	(_('Ambatomainty'), _("It's in %s") % _('Fianarantsoa')),
	(_('Mahela'), _("It's in %s") % _('Fianarantsoa')),
	(_('Mananjary'), _("It's in %s") % _('Fianarantsoa')),
	(_('Ampasimanjeva'), _("It's in %s") % _('Fianarantsoa')),
	(_('Sahasinaka'), _("It's in %s") % _('Fianarantsoa')),
	(_('Manakara'), _("It's in %s") % _('Fianarantsoa')),
	(_('Menamaty Lloto'), _("It's in %s") % _('Fianarantsoa')),
	(_('Vohipeno'), _("It's in %s") % _('Fianarantsoa')),
	(_('Ranohira'), _("It's in %s") % _('Fianarantsoa')),
	(_('Farafangana'), _("It's in %s") % _('Fianarantsoa')),
    (_('Nosy Be'), _("It's a island"))
]
]

LEVEL4 = [
        4,
        _('Waterways'),
        ['lineasDepto', 'rios'],
        [],
[
    #(_('xxx River'), _('Is in the center')),

]
]

LEVELS = [LEVEL1]

